// Reads version from deno.json and patches public/sw.js — the CACHE name, which
// forces the browser to bust the service worker cache on every version bump.
//
// It used to also patch public/config.js. That was dead work: nothing copies
// public/config.js into dist/. The shipped dist/config.js is generated by
// scripts/write-config.ts, which reads the version from deno.json directly.
//
// Run via: deno task sync:version
// Called automatically by deno task build and deno task dev.

const { version } = JSON.parse(await Deno.readTextFile('deno.json')) as { version: string };

// Patch public/sw.js cache name so any version bump forces a full SW cache bust
const swPath = 'public/sw.js';
const swSrc = await Deno.readTextFile(swPath);
const swUpdated = swSrc.replace(
  /(const CACHE\s*=\s*')leptonpad-v[^']*(')/,
  `$1leptonpad-v${version}$2`,
);
if (swUpdated !== swSrc) {
  await Deno.writeTextFile(swPath, swUpdated);
  console.log(`sync:version — public/sw.js cache updated to leptonpad-v${version}`);
}
