// ---------------------------------------------------------------------------
// write-config.ts — generates dist/config.js, the runtime config the browser
// reads as globalThis.__LP_CONFIG__ before main.js executes.
//
// Single source for both build.ts and dev.ts; they used to carry near-identical
// copies of this logic that could drift apart.
//
// Values resolve in order: process env (set these in Vercel / Deno Deploy),
// then a local .env file, then a harmless placeholder. Everything written here
// is PUBLIC — it ships to every browser. Publishable keys only; never a secret
// key, never a database URL.
// ---------------------------------------------------------------------------

/** Reads KEY=value pairs from a .env file. Returns {} when there is no file. */
async function readEnvFile(path = '.env'): Promise<Record<string, string>> {
  try {
    const out: Record<string, string> = {};
    const text = await Deno.readTextFile(path);
    for (const line of text.split('\n')) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      const [k, ...rest] = trimmed.split('=');
      out[k.trim()] = rest.join('=').trim();
    }
    return out;
  } catch {
    return {};
  }
}

/**
 * Renders the `__LP_CONFIG__` script from the environment.
 *
 * Shared by the build (writes `dist/config.js`) and the production server, which
 * serves it fresh per request — see `main.ts`. One definition so the two can
 * never disagree about what the browser is handed.
 *
 * `envFile` is the parsed `.env` for local work; production passes nothing and
 * reads the process environment alone.
 */
export function renderConfigJs(version: string, envFile: Record<string, string> = {}): string {
  const pick = (key: string, fallback: string) => Deno.env.get(key) || envFile[key] || fallback;

  const cfg = {
    // Clerk — identity. Publishable key is safe to expose by design.
    clerkPublishableKey: pick('CLERK_PUBLISHABLE_KEY', ''),

    // Where the entitlement API lives, no trailing slash.
    //
    // Defaults to the RELATIVE "/api", which is where main.ts mounts it in
    // production — same origin, so no CORS and no env var needed there. Local
    // dev overrides it in .env to http://localhost:8000, because `deno task dev`
    // serves the site on :5173 and the API runs separately.
    apiBaseUrl: pick('LP_API_URL', '/api'),

    version,
  };

  const body = Object.entries(cfg)
    .map(([k, v]) => `  ${k}: ${JSON.stringify(v)},`)
    .join('\n');

  return `// Generated by scripts/write-config.ts — do not edit by hand.\n` +
    `globalThis.__LP_CONFIG__ = {\n${body}\n};\n`;
}

/** Writes dist/config.js. `version` comes from deno.json. */
export async function writeConfigJs(version: string, outPath = 'dist/config.js'): Promise<void> {
  await Deno.writeTextFile(outPath, renderConfigJs(version, await readEnvFile()));
}
